// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA17A12wODu91p3vXxp24ZqqCZC6G8eVp4',
    appId: '1:753094060640:web:f632a2930fb42d23703105',
    messagingSenderId: '753094060640',
    projectId: 'sarava-3d42d',
    authDomain: 'sarava-3d42d.firebaseapp.com',
    storageBucket: 'sarava-3d42d.appspot.com',
    measurementId: 'G-MXTNEQZ17P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlPlbsQP5XMTT0rNrSsjGMCx3Nl7XqO5c',
    appId: '1:753094060640:android:24a950bb1dd8a81f703105',
    messagingSenderId: '753094060640',
    projectId: 'sarava-3d42d',
    storageBucket: 'sarava-3d42d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDqgN1a4JkuY4KLSItujbW41x85yZpTOQ',
    appId: '1:753094060640:ios:4da48450ff979667703105',
    messagingSenderId: '753094060640',
    projectId: 'sarava-3d42d',
    storageBucket: 'sarava-3d42d.appspot.com',
    iosBundleId: 'br.com.sarava.sarava',
  );
}
